# Generated by Django 4.0.2 on 2022-02-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_phonenumber_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='phone_number',
            new_name='phone_numbers',
        ),
    ]
