# Generated by Django 4.0.2 on 2022-02-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_phonenumber_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='phone_numbers',
            new_name='phone_number',
        ),
    ]
