# Generated by Django 4.0.3 on 2022-03-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_rename_phone_numbers_phonenumber_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_id', models.CharField(max_length=200)),
            ],
        ),
    ]
