# Generated by Django 4.0.2 on 2022-02-28 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='site',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(max_length=500),
        ),
    ]
