# Generated by Django 4.0.2 on 2022-02-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_phone_number_phonenumber_phone_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
